---
name: CI/CD
on:
  pull_request:
    branches:
      - main
    paths:
      - '**/Dockerfile'
  schedule:
    - cron: '0 18 * * 0'
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
 
jobs:
  test_and_build:
    runs-on: [ self-hosted ]
    name: Code check and build container, no push
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        os: [ centos7, ubuntu1404, ubuntu1604, ubuntu1804, ubuntu2004, ubuntu2204, debian8, debian9, debian10, debian11, debian12, alpine-edge, alpine-latest ]
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Change ownership
        run: |
          sudo chown -R $(whoami):$(whoami) $GITHUB_WORKSPACE

      - name: Checkout the codebase
        uses: actions/checkout@v3

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.os }}/Dockerfile
          ignore: SC2086, DL3008, DL3013, DL3002, DL3007, DL3018, DL3033, SC3037, DL3059, SC2039, DL3018, DL3033

  build_container:
    name: Build container based on matrix
    needs: [ test_and_build ]
    runs-on: [ qemu ]
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        os: [ centos7, ubuntu1404, ubuntu1604, ubuntu1804, ubuntu2004, ubuntu2204, debian8, debian9, debian10, debian11, debian12, alpine-edge, alpine-latest ]
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Change ownership
        run: |
          sudo chown -R $(whoami):$(whoami) $GITHUB_WORKSPACE

      - name: Checkout the codebase
        uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses:  docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ${{ matrix.os }}/Dockerfile
          platforms: linux/amd64
          push: true
          pull: true
          tags: udienz/docker-buildpack:${{ matrix.os }}
